name: diploma
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-259.12.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  flash: ^1.4.0-nullsafety
  flutter_bloc: ^7.0.0-nullsafety.2
  flutter_staggered_grid_view: ^0.4.0-nullsafety.2
  freezed_annotation: ^0.14.0
  hive: ^1.6.0-nullsafety.2
  hive_flutter: ^1.0.0-nullsafety.0
  image_picker: ^0.7.0
  path_provider: ^2.0.0
  uuid: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  freezed: ^0.14.0
  hive_generator: ^0.9.0-nullsafety.1
  lint: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Arista
      fonts:
        - asset: assets/fonts/arista-pro.ttf
